imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: admin/ }
    - { resource: configs/ }
    - { resource: "@IRUserBundle/Resources/config/services.yml" }    
    - { resource: "@ApiBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    mail_from: noreply@instructiveride.com   
    admin_email: contact@http5000.com   

services:
    fos_user.doctrine_registry:
        alias: doctrine
    
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true
    serializer:
        enabled: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
         google_map_api_key: "%google_map_api_key%"
         base_url: "%base_url%"
         footer_address: "%footer_address%"
         footer_phone: "%footer_phone%"
         footer_link: "%footer_link%"
         footer_facebook: "%footer_facebook%"
         footer_twitter: "%footer_twitter%"
         footer_instagram: "%footer_instagram%"
         footer_contact_us: "%footer_contact_us%"
         footer_copyright: "%footer_copyright%"
         footer_TermCondition: "%footer_TermCondition%"
         footer_TermCondition_fr: "%footer_TermCondition_fr%"
         footer_Legalmention: "%footer_Legalmention%"
         footer_Legalmention_fr: "%footer_Legalmention_fr%"
         footer_TermCondition_link: "%footer_TermCondition_link%"
         footer_TermCondition_fr: "%footer_TermCondition_fr%"
         footer_Legalmention_link: "%footer_Legalmention_link%"
         footer_Legalmention_fr: "%footer_Legalmention_fr%"
         footer_About: "%footer_About%"
         footer_About_fr: "%footer_About_fr%"
         footer_faq: "%footer_faq%"
         footer_faq_fr: "%footer_faq_fr%"
         footer_help_en: "%footer_help_en%"
         footer_help_fr: "%footer_help_fr%"
         locales: [en, fr]
         cache:  false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        # only these lines are added additionally
        mappings:
            translatable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Translatable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                is_bundle: false

stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
#    port: %mailer_port%
#    encryption: %mailer_encryption%
    username:  "%mailer_user%"
    password:  "%mailer_password%"    
    spool:     { type: memory }

# FOSUserBundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: IR\UserBundle\Entity\User
    resetting:
        email:
            template:   email/password_resetting.email.twig
            from_email:
                address:        noreply@instructiveride.com
                sender_name:    Team Instructive Ride
    registration:
        form:
            type: IR\UserBundle\Form\RegistrationType
        confirmation:
            enabled: true
#            template:   FOSUserBundle:Registration:email.txt.twig
            from_email:
                address:        noreply@instructiveride.com
                sender_name:    Team Instructive Ride
    service:
        mailer: fos_user.mailer.twig_swift
    profile:
            form:
                type: IR\UserBundle\Form\ProfileType                
    group:
        group_class: IR\UserBundle\Entity\Group

jms_i18n_routing:
    default_locale: en
    locales: [en, fr]
    strategy: prefix

assetic:
    debug:          '%kernel.debug%'
    use_controller: false
    filters:
        cssrewrite: ~
#nelmio_api_doc: ~
#fos_rest:
#    format_listener:
#          rules:
#              - { path: ^/api/, priorities: [ html, json, xml ], fallback_format: ~, prefer_extension: true }
#    routing_loader:
#        default_format: json
#    param_fetcher_listener: true
#    view:
#        view_response_listener: 'force'
#        formats:
#            xml: true
#            json: true
#        templating_formats:
#            html: true