api:
    resource: "@ApiBundle/Resources/config/routing.yml"
    prefix:   /api
    options: { i18n: false }
app:
    resource: "@IRRideBundle/Resources/config/routing.yml"
    prefix:   /
    
ir_user:
    resource: "@IRUserBundle/Resources/config/routing.yml"
    prefix:   /profile

easy_admin_bundle:
    resource: "@IRUserBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin-back-front
    options: { i18n: false }

#FosUserBundle Routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_logout:
    path: /logout

#HWIOAuthBundle routes
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

facebook_login:
    path: /login_facebook

google_login:
    path: /login_google

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

ir_user_fav:
    path:     /favorite
    defaults: { _controller: IRUserBundle:Favorite:index }
ir_user_ride_history:
    path:     /history
    defaults: { _controller: IRUserBundle:Ride:history }   
ir_test:
    path:     /welcome
    defaults: { _controller: IRUserBundle:Registration:welcome }   
admin_ride_validate:
    path:     /rideValidate
    defaults: { _controller: IRUserBundle:Ride:rideStatus }
    methods:  [GET, POST]
get_admin_rides:
    path:     /getAllRides
    defaults: { _controller: IRUserBundle:SuperAdmin:getAllRides }
get_all_users:
    path:     /gelAllusers
    defaults: { _controller: IRUserBundle:SuperAdmin:getAllUser }
get_ot_users:
    path:     /tourism_office
    defaults: { _controller: IRUserBundle:SuperAdmin:getOtUsers }

# show one ride
ir_ride_show:
    path:     /{slug}
    defaults: { _controller: IRRideBundle:Ride:show }
    methods:  [GET]
    options: { i18n: false }
#NelmioApiDocBundle:
#    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
#    prefix:   /api/doc
#    options: { i18n: false }