parameters:
    my_user_provider.class: IR\UserBundle\Security\Core\User\FOSUBUserProvider


services:
    test.loging:
        class: IR\UserBundle\Services\LogTestService
        arguments: ["@service_container"]

    ir.form.flow.createRide:
        class: IR\UserBundle\Form\RegisterUser
